name: Update Daily News

on:
  # 1. Chạy tự động theo lịch
  schedule:
    # Chạy vào 01:00 UTC mỗi ngày, tương đương 8:00 sáng giờ Việt Nam (UTC+7)
    - cron: '0 1 * * *'
    
  # 2. Cho phép chạy thủ công từ tab Actions trên GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy mã nguồn từ repository về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Có thể dùng '3.x'

      # Bước 3: Cài đặt các thư viện cần thiết từ tệp requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước 4: Chạy script Python chính để lấy tin và tạo file index.html
      - name: Run script to fetch news and generate HTML
        run: python main.py

      # Bước 5: Tự động commit và đẩy tệp index.html mới lên repository
      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Cập nhật tin tức tự động"
          file_pattern: index.html
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"